// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1PLFqvXHMH4v8MsDrTfjDkxhwg9uYTlE',
    appId: '1:663509823079:web:580ced618630aeafe42ec2',
    messagingSenderId: '663509823079',
    projectId: 'comaplaint1',
    authDomain: 'comaplaint1.firebaseapp.com',
    storageBucket: 'comaplaint1.firebasestorage.app',
    measurementId: 'G-Q4BC6WYWTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALbN6aQftIodwXpZmdIRzO0JDSUhD4ojk',
    appId: '1:663509823079:android:f919160ed188bc2ee42ec2',
    messagingSenderId: '663509823079',
    projectId: 'comaplaint1',
    storageBucket: 'comaplaint1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1PLFqvXHMH4v8MsDrTfjDkxhwg9uYTlE',
    appId: '1:663509823079:web:ec454bce8a17cc33e42ec2',
    messagingSenderId: '663509823079',
    projectId: 'comaplaint1',
    authDomain: 'comaplaint1.firebaseapp.com',
    storageBucket: 'comaplaint1.firebasestorage.app',
    measurementId: 'G-0BFGGLYKJF',
  );
}
